### ISSUE TITLE
Игра не готова!

### ISSUE THREAD

**Issue by He4eT** [Bananaft/UGJ#1]
Привет! Молодец, что завел репозиторий.
Готовность демо-версии можно обозначить комментарием к этом Issue, а релиз - закрытием.
Успехов и идей =)

**Comment by Bananaft** [comment]
вот демка:
https://dl.dropboxusercontent.com/u/8845134/dev/UGJ/003/pronus.zip

**Comment by Bananaft** [comment]
Финальная версия на момент окончания джема:
https://dl.dropboxusercontent.com/u/8845134/dev/UGJ/004/Pronus.zip
